from app.models import Country
from app.extensions import db

COUNTRIES_DATA = [
  {'name': 'Afghanistan', 'code': 'AF', 'flag': '🇦🇫', 'continent': 'Asia'},
  {'name': 'Albania', 'code': 'AL', 'flag': '🇦🇱', 'continent': 'Europe'},
  {'name': 'Algeria', 'code': 'DZ', 'flag': '🇩🇿', 'continent': 'Africa'},
  {'name': 'Andorra', 'code': 'AD', 'flag': '🇦🇩', 'continent': 'Europe'},
  {'name': 'Angola', 'code': 'AO', 'flag': '🇦🇴', 'continent': 'Africa'},
  {'name': 'Antigua and Barbuda', 'code': 'AG', 'flag': '🇦🇬', 'continent': 'North America'},
  {'name': 'Argentina', 'code': 'AR', 'flag': '🇦🇷', 'continent': 'South America'},
  {'name': 'Armenia', 'code': 'AM', 'flag': '🇦🇲', 'continent': 'Asia'},
  {'name': 'Australia', 'code': 'AU', 'flag': '🇦🇺', 'continent': 'Oceania'},
  {'name': 'Austria', 'code': 'AT', 'flag': '🇦🇹', 'continent': 'Europe'},
  {'name': 'Azerbaijan', 'code': 'AZ', 'flag': '🇦🇿', 'continent': 'Asia'},
  {'name': 'Bahamas', 'code': 'BS', 'flag': '🇧🇸', 'continent': 'North America'},
  {'name': 'Bahrain', 'code': 'BH', 'flag': '🇧🇭', 'continent': 'Asia'},
  {'name': 'Bangladesh', 'code': 'BD', 'flag': '🇧🇩', 'continent': 'Asia'},
  {'name': 'Barbados', 'code': 'BB', 'flag': '🇧🇧', 'continent': 'North America'},
  {'name': 'Belarus', 'code': 'BY', 'flag': '🇧🇾', 'continent': 'Europe'},
  {'name': 'Belgium', 'code': 'BE', 'flag': '🇧🇪', 'continent': 'Europe'},
  {'name': 'Belize', 'code': 'BZ', 'flag': '🇧🇿', 'continent': 'North America'},
  {'name': 'Benin', 'code': 'BJ', 'flag': '🇧🇯', 'continent': 'Africa'},
  {'name': 'Bhutan', 'code': 'BT', 'flag': '🇧🇹', 'continent': 'Asia'},
  {'name': 'Bolivia', 'code': 'BO', 'flag': '🇧🇴', 'continent': 'South America'},
  {'name': 'Bosnia and Herzegovina', 'code': 'BA', 'flag': '🇧🇦', 'continent': 'Europe'},
  {'name': 'Botswana', 'code': 'BW', 'flag': '🇧🇼', 'continent': 'Africa'},
  {'name': 'Brazil', 'code': 'BR', 'flag': '🇧🇷', 'continent': 'South America'},
  {'name': 'Brunei', 'code': 'BN', 'flag': '🇧🇳', 'continent': 'Asia'},
  {'name': 'Bulgaria', 'code': 'BG', 'flag': '🇧🇬', 'continent': 'Europe'},
  {'name': 'Burkina Faso', 'code': 'BF', 'flag': '🇧🇫', 'continent': 'Africa'},
  {'name': 'Burundi', 'code': 'BI', 'flag': '🇧🇮', 'continent': 'Africa'},
  {'name': 'Cabo Verde', 'code': 'CV', 'flag': '🇨🇻', 'continent': 'Africa'},
  {'name': 'Cambodia', 'code': 'KH', 'flag': '🇰🇭', 'continent': 'Asia'},
  {'name': 'Cameroon', 'code': 'CM', 'flag': '🇨🇲', 'continent': 'Africa'},
  {'name': 'Canada', 'code': 'CA', 'flag': '🇨🇦', 'continent': 'North America'},
  {'name': 'Central African Republic', 'code': 'CF', 'flag': '🇨🇫', 'continent': 'Africa'},
  {'name': 'Chad', 'code': 'TD', 'flag': '🇹🇩', 'continent': 'Africa'},
  {'name': 'Chile', 'code': 'CL', 'flag': '🇨🇱', 'continent': 'South America'},
  {'name': 'China', 'code': 'CN', 'flag': '🇨🇳', 'continent': 'Asia'},
  {'name': 'Colombia', 'code': 'CO', 'flag': '🇨🇴', 'continent': 'South America'},
  {'name': 'Comoros', 'code': 'KM', 'flag': '🇰🇲', 'continent': 'Africa'},
  {'name': 'Congo (Brazzaville)', 'code': 'CG', 'flag': '🇨🇬', 'continent': 'Africa'},
  {'name': 'Congo (Kinshasa)', 'code': 'CD', 'flag': '🇨🇩', 'continent': 'Africa'},
  {'name': 'Costa Rica', 'code': 'CR', 'flag': '🇨🇷', 'continent': 'North America'},
  {'name': 'Croatia', 'code': 'HR', 'flag': '🇭🇷', 'continent': 'Europe'},
  {'name': 'Cuba', 'code': 'CU', 'flag': '🇨🇺', 'continent': 'North America'},
  {'name': 'Cyprus', 'code': 'CY', 'flag': '🇨🇾', 'continent': 'Asia'},
  {'name': 'Czech Republic', 'code': 'CZ', 'flag': '🇨🇿', 'continent': 'Europe'},
  {'name': 'Denmark', 'code': 'DK', 'flag': '🇩🇰', 'continent': 'Europe'},
  {'name': 'Djibouti', 'code': 'DJ', 'flag': '🇩🇯', 'continent': 'Africa'},
  {'name': 'Dominica', 'code': 'DM', 'flag': '🇩🇲', 'continent': 'North America'},
  {'name': 'Dominican Republic', 'code': 'DO', 'flag': '🇩🇴', 'continent': 'North America'},
  {'name': 'Ecuador', 'code': 'EC', 'flag': '🇪🇨', 'continent': 'South America'},
  {'name': 'Egypt', 'code': 'EG', 'flag': '🇪🇬', 'continent': 'Africa'},
  {'name': 'El Salvador', 'code': 'SV', 'flag': '🇸🇻', 'continent': 'North America'},
  {'name': 'Equatorial Guinea', 'code': 'GQ', 'flag': '🇬🇶', 'continent': 'Africa'},
  {'name': 'Eritrea', 'code': 'ER', 'flag': '🇪🇷', 'continent': 'Africa'},
  {'name': 'Estonia', 'code': 'EE', 'flag': '🇪🇪', 'continent': 'Europe'},
  {'name': 'Eswatini', 'code': 'SZ', 'flag': '🇸🇿', 'continent': 'Africa'},
  {'name': 'Ethiopia', 'code': 'ET', 'flag': '🇪🇹', 'continent': 'Africa'},
  {'name': 'Fiji', 'code': 'FJ', 'flag': '🇫🇯', 'continent': 'Oceania'},
  {'name': 'Finland', 'code': 'FI', 'flag': '🇫🇮', 'continent': 'Europe'},
  {'name': 'France', 'code': 'FR', 'flag': '🇫🇷', 'continent': 'Europe'},
  {'name': 'Gabon', 'code': 'GA', 'flag': '🇬🇦', 'continent': 'Africa'},
  {'name': 'Gambia', 'code': 'GM', 'flag': '🇬🇲', 'continent': 'Africa'},
  {'name': 'Georgia', 'code': 'GE', 'flag': '🇬🇪', 'continent': 'Asia'},
  {'name': 'Germany', 'code': 'DE', 'flag': '🇩🇪', 'continent': 'Europe'},
  {'name': 'Ghana', 'code': 'GH', 'flag': '🇬🇭', 'continent': 'Africa'},
  {'name': 'Greece', 'code': 'GR', 'flag': '🇬🇷', 'continent': 'Europe'},
  {'name': 'Grenada', 'code': 'GD', 'flag': '🇬🇩', 'continent': 'North America'},
  {'name': 'Guatemala', 'code': 'GT', 'flag': '🇬🇹', 'continent': 'North America'},
  {'name': 'Guinea', 'code': 'GN', 'flag': '🇬🇳', 'continent': 'Africa'},
  {'name': 'Guinea-Bissau', 'code': 'GW', 'flag': '🇬🇼', 'continent': 'Africa'},
  {'name': 'Guyana', 'code': 'GY', 'flag': '🇬🇾', 'continent': 'South America'},
  {'name': 'Haiti', 'code': 'HT', 'flag': '🇭🇹', 'continent': 'North America'},
  {'name': 'Honduras', 'code': 'HN', 'flag': '🇭🇳', 'continent': 'North America'},
  {'name': 'Hungary', 'code': 'HU', 'flag': '🇭🇺', 'continent': 'Europe'},
  {'name': 'Iceland', 'code': 'IS', 'flag': '🇮🇸', 'continent': 'Europe'},
  {'name': 'India', 'code': 'IN', 'flag': '🇮🇳', 'continent': 'Asia'},
  {'name': 'Indonesia', 'code': 'ID', 'flag': '🇮🇩', 'continent': 'Asia'},
  {'name': 'Iran', 'code': 'IR', 'flag': '🇮🇷', 'continent': 'Asia'},
  {'name': 'Iraq', 'code': 'IQ', 'flag': '🇮🇶', 'continent': 'Asia'},
  {'name': 'Ireland', 'code': 'IE', 'flag': '🇮🇪', 'continent': 'Europe'},
  {'name': 'Israel', 'code': 'IL', 'flag': '🇮🇱', 'continent': 'Asia'},
  {'name': 'Italy', 'code': 'IT', 'flag': '🇮🇹', 'continent': 'Europe'},
  {'name': 'Jamaica', 'code': 'JM', 'flag': '🇯🇲', 'continent': 'North America'},
  {'name': 'Japan', 'code': 'JP', 'flag': '🇯🇵', 'continent': 'Asia'},
  {'name': 'Jordan', 'code': 'JO', 'flag': '🇯🇴', 'continent': 'Asia'},
  {'name': 'Kazakhstan', 'code': 'KZ', 'flag': '🇰🇿', 'continent': 'Asia'},
  {'name': 'Kenya', 'code': 'KE', 'flag': '🇰🇪', 'continent': 'Africa'},
  {'name': 'Kiribati', 'code': 'KI', 'flag': '🇰🇮', 'continent': 'Oceania'},
  {'name': 'Kosovo', 'code': 'XK', 'flag': '🇽🇰', 'continent': 'Europe'},
  {'name': 'Kuwait', 'code': 'KW', 'flag': '🇰🇼', 'continent': 'Asia'},
  {'name': 'Kyrgyzstan', 'code': 'KG', 'flag': '🇰🇬', 'continent': 'Asia'},
  {'name': 'Laos', 'code': 'LA', 'flag': '🇱🇦', 'continent': 'Asia'},
  {'name': 'Latvia', 'code': 'LV', 'flag': '🇱🇻', 'continent': 'Europe'},
  {'name': 'Lebanon', 'code': 'LB', 'flag': '🇱🇧', 'continent': 'Asia'},
  {'name': 'Lesotho', 'code': 'LS', 'flag': '🇱🇸', 'continent': 'Africa'},
  {'name': 'Liberia', 'code': 'LR', 'flag': '🇱🇷', 'continent': 'Africa'},
  {'name': 'Libya', 'code': 'LY', 'flag': '🇱🇾', 'continent': 'Africa'},
  {'name': 'Liechtenstein', 'code': 'LI', 'flag': '🇱🇮', 'continent': 'Europe'},
  {'name': 'Lithuania', 'code': 'LT', 'flag': '🇱🇹', 'continent': 'Europe'},
  {'name': 'Luxembourg', 'code': 'LU', 'flag': '🇱🇺', 'continent': 'Europe'},
  {'name': 'Madagascar', 'code': 'MG', 'flag': '🇲🇬', 'continent': 'Africa'},
  {'name': 'Malawi', 'code': 'MW', 'flag': '🇲🇼', 'continent': 'Africa'},
  {'name': 'Malaysia', 'code': 'MY', 'flag': '🇲🇾', 'continent': 'Asia'},
  {'name': 'Maldives', 'code': 'MV', 'flag': '🇲🇻', 'continent': 'Asia'},
  {'name': 'Mali', 'code': 'ML', 'flag': '🇲🇱', 'continent': 'Africa'},
  {'name': 'Malta', 'code': 'MT', 'flag': '🇲🇹', 'continent': 'Europe'},
  {'name': 'Marshall Islands', 'code': 'MH', 'flag': '🇲🇭', 'continent': 'Oceania'},
  {'name': 'Mauritania', 'code': 'MR', 'flag': '🇲🇷', 'continent': 'Africa'},
  {'name': 'Mauritius', 'code': 'MU', 'flag': '🇲🇺', 'continent': 'Africa'},
  {'name': 'Mexico', 'code': 'MX', 'flag': '🇲🇽', 'continent': 'North America'},
  {'name': 'Micronesia', 'code': 'FM', 'flag': '🇫🇲', 'continent': 'Oceania'},
  {'name': 'Moldova', 'code': 'MD', 'flag': '🇲🇩', 'continent': 'Europe'},
  {'name': 'Monaco', 'code': 'MC', 'flag': '🇲🇨', 'continent': 'Europe'},
  {'name': 'Mongolia', 'code': 'MN', 'flag': '🇲🇳', 'continent': 'Asia'},
  {'name': 'Montenegro', 'code': 'ME', 'flag': '🇲🇪', 'continent': 'Europe'},
  {'name': 'Morocco', 'code': 'MA', 'flag': '🇲🇦', 'continent': 'Africa'},
  {'name': 'Mozambique', 'code': 'MZ', 'flag': '🇲🇿', 'continent': 'Africa'},
  {'name': 'Myanmar', 'code': 'MM', 'flag': '🇲🇲', 'continent': 'Asia'},
  {'name': 'Namibia', 'code': 'NA', 'flag': '🇳🇦', 'continent': 'Africa'},
  {'name': 'Nauru', 'code': 'NR', 'flag': '🇳🇷', 'continent': 'Oceania'},
  {'name': 'Nepal', 'code': 'NP', 'flag': '🇳🇵', 'continent': 'Asia'},
  {'name': 'Netherlands', 'code': 'NL', 'flag': '🇳🇱', 'continent': 'Europe'},
  {'name': 'New Zealand', 'code': 'NZ', 'flag': '🇳🇿', 'continent': 'Oceania'},
  {'name': 'Nicaragua', 'code': 'NI', 'flag': '🇳🇮', 'continent': 'North America'},
  {'name': 'Niger', 'code': 'NE', 'flag': '🇳🇪', 'continent': 'Africa'},
  {'name': 'Nigeria', 'code': 'NG', 'flag': '🇳🇬', 'continent': 'Africa'},
  {'name': 'North Korea', 'code': 'KP', 'flag': '🇰🇵', 'continent': 'Asia'},
  {'name': 'North Macedonia', 'code': 'MK', 'flag': '🇲🇰', 'continent': 'Europe'},
  {'name': 'Norway', 'code': 'NO', 'flag': '🇳🇴', 'continent': 'Europe'},
  {'name': 'Oman', 'code': 'OM', 'flag': '🇴🇲', 'continent': 'Asia'},
  {'name': 'Pakistan', 'code': 'PK', 'flag': '🇵🇰', 'continent': 'Asia'},
  {'name': 'Palau', 'code': 'PW', 'flag': '🇵🇼', 'continent': 'Oceania'},
  {'name': 'Palestine', 'code': 'PS', 'flag': '🇵🇸', 'continent': 'Asia'},
  {'name': 'Panama', 'code': 'PA', 'flag': '🇵🇦', 'continent': 'North America'},
  {'name': 'Papua New Guinea', 'code': 'PG', 'flag': '🇵🇬', 'continent': 'Oceania'},
  {'name': 'Paraguay', 'code': 'PY', 'flag': '🇵🇾', 'continent': 'South America'},
  {'name': 'Peru', 'code': 'PE', 'flag': '🇵🇪', 'continent': 'South America'},
  {'name': 'Philippines', 'code': 'PH', 'flag': '🇵🇭', 'continent': 'Asia'},
  {'name': 'Poland', 'code': 'PL', 'flag': '🇵🇱', 'continent': 'Europe'},
  {'name': 'Portugal', 'code': 'PT', 'flag': '🇵🇹', 'continent': 'Europe'},
  {'name': 'Qatar', 'code': 'QA', 'flag': '🇶🇦', 'continent': 'Asia'},
  {'name': 'Romania', 'code': 'RO', 'flag': '🇷🇴', 'continent': 'Europe'},
  {'name': 'Russia', 'code': 'RU', 'flag': '🇷🇺', 'continent': 'Europe'},
  {'name': 'Rwanda', 'code': 'RW', 'flag': '🇷🇼', 'continent': 'Africa'},
  {'name': 'Saint Kitts and Nevis', 'code': 'KN', 'flag': '🇰🇳', 'continent': 'North America'},
  {'name': 'Saint Lucia', 'code': 'LC', 'flag': '🇱🇨', 'continent': 'North America'},
  {'name': 'Saint Vincent and the Grenadines', 'code': 'VC', 'flag': '🇻🇨', 'continent': 'North America'},
  {'name': 'Samoa', 'code': 'WS', 'flag': '🇼🇸', 'continent': 'Oceania'},
  {'name': 'San Marino', 'code': 'SM', 'flag': '🇸🇲', 'continent': 'Europe'},
  {'name': 'Sao Tome and Principe', 'code': 'ST', 'flag': '🇸🇹', 'continent': 'Africa'},
  {'name': 'Saudi Arabia', 'code': 'SA', 'flag': '🇸🇦', 'continent': 'Asia'},
  {'name': 'Senegal', 'code': 'SN', 'flag': '🇸🇳', 'continent': 'Africa'},
  {'name': 'Serbia', 'code': 'RS', 'flag': '🇷🇸', 'continent': 'Europe'},
  {'name': 'Seychelles', 'code': 'SC', 'flag': '🇸🇨', 'continent': 'Africa'},
  {'name': 'Sierra Leone', 'code': 'SL', 'flag': '🇸🇱', 'continent': 'Africa'},
  {'name': 'Singapore', 'code': 'SG', 'flag': '🇸🇬', 'continent': 'Asia'},
  {'name': 'Slovakia', 'code': 'SK', 'flag': '🇸🇰', 'continent': 'Europe'},
  {'name': 'Slovenia', 'code': 'SI', 'flag': '🇸🇮', 'continent': 'Europe'},
  {'name': 'Solomon Islands', 'code': 'SB', 'flag': '🇸🇧', 'continent': 'Oceania'},
  {'name': 'Somalia', 'code': 'SO', 'flag': '🇸🇴', 'continent': 'Africa'},
  {'name': 'South Africa', 'code': 'ZA', 'flag': '🇿🇦', 'continent': 'Africa'},
  {'name': 'South Korea', 'code': 'KR', 'flag': '🇰🇷', 'continent': 'Asia'},
  {'name': 'South Sudan', 'code': 'SS', 'flag': '🇸🇸', 'continent': 'Africa'},
  {'name': 'Spain', 'code': 'ES', 'flag': '🇪🇸', 'continent': 'Europe'},
  {'name': 'Sri Lanka', 'code': 'LK', 'flag': '🇱🇰', 'continent': 'Asia'},
  {'name': 'Sudan', 'code': 'SD', 'flag': '🇸🇩', 'continent': 'Africa'},
  {'name': 'Suriname', 'code': 'SR', 'flag': '🇸🇷', 'continent': 'South America'},
  {'name': 'Sweden', 'code': 'SE', 'flag': '🇸🇪', 'continent': 'Europe'},
  {'name': 'Switzerland', 'code': 'CH', 'flag': '🇨🇭', 'continent': 'Europe'},
  {'name': 'Syria', 'code': 'SY', 'flag': '🇸🇾', 'continent': 'Asia'},
  {'name': 'Taiwan', 'code': 'TW', 'flag': '🇹🇼', 'continent': 'Asia'},
  {'name': 'Tajikistan', 'code': 'TJ', 'flag': '🇹🇯', 'continent': 'Asia'},
  {'name': 'Tanzania', 'code': 'TZ', 'flag': '🇹🇿', 'continent': 'Africa'},
  {'name': 'Thailand', 'code': 'TH', 'flag': '🇹🇭', 'continent': 'Asia'},
  {'name': 'Togo', 'code': 'TG', 'flag': '🇹🇬', 'continent': 'Africa'},
  {'name': 'Tonga', 'code': 'TO', 'flag': '🇹🇴', 'continent': 'Oceania'},
  {'name': 'Trinidad and Tobago', 'code': 'TT', 'flag': '🇹🇹', 'continent': 'North America'},
  {'name': 'Tunisia', 'code': 'TN', 'flag': '🇹🇳', 'continent': 'Africa'},
  {'name': 'Turkey', 'code': 'TR', 'flag': '🇹🇷', 'continent': 'Asia'},
  {'name': 'Turkmenistan', 'code': 'TM', 'flag': '🇹🇲', 'continent': 'Asia'},
  {'name': 'Tuvalu', 'code': 'TV', 'flag': '🇹🇻', 'continent': 'Oceania'},
  {'name': 'Uganda', 'code': 'UG', 'flag': '🇺🇬', 'continent': 'Africa'},
  {'name': 'Ukraine', 'code': 'UA', 'flag': '🇺🇦', 'continent': 'Europe'},
  {'name': 'United Arab Emirates', 'code': 'AE', 'flag': '🇦🇪', 'continent': 'Asia'},
  {'name': 'United Kingdom', 'code': 'GB', 'flag': '🇬🇧', 'continent': 'Europe'},
  {'name': 'United States', 'code': 'US', 'flag': '🇺🇸', 'continent': 'North America'},
  {'name': 'Uruguay', 'code': 'UY', 'flag': '🇺🇾', 'continent': 'South America'},
  {'name': 'Uzbekistan', 'code': 'UZ', 'flag': '🇺🇿', 'continent': 'Asia'},
  {'name': 'Vanuatu', 'code': 'VU', 'flag': '🇻🇺', 'continent': 'Oceania'},
  {'name': 'Vatican City', 'code': 'VA', 'flag': '🇻🇦', 'continent': 'Europe'},
  {'name': 'Venezuela', 'code': 'VE', 'flag': '🇻🇪', 'continent': 'South America'},
  {'name': 'Vietnam', 'code': 'VN', 'flag': '🇻🇳', 'continent': 'Asia'},
  {'name': 'Yemen', 'code': 'YE', 'flag': '🇾🇪', 'continent': 'Asia'},
  {'name': 'Zambia', 'code': 'ZM', 'flag': '🇿🇲', 'continent': 'Africa'},
  {'name': 'Zimbabwe', 'code': 'ZW', 'flag': '🇿🇼', 'continent': 'Africa'}
]

def import_countries():
  existing_count = Country.query.count()

  if existing_count > 0:
    return {'imported': 0, 'updated': 0, 'message': 'Countries already exist, skipping import'}

  imported = 0

  for country_data in COUNTRIES_DATA:
    country = Country(
      name=country_data['name'],
      code=country_data['code'],
      flag=country_data['flag'],
      continent=country_data['continent']
    )
    db.session.add(country)
    imported += 1

  db.session.commit()
  return {'imported': imported, 'updated': 0, 'message': f'Imported {imported} countries'}

